const types = {
  FILTERS__SET_BOOLEAN_FILTERS: "FILTERS__SET_BOOLEAN_FILTERS",
  FILTERS__SET_NOTBOOLEAN_FILTERS: "FILTERS__SET_NOTBOOLEAN_FILTERS",
  FILTERS__REMOVE_NOTBOOLEAN_FILTERS: "FILTERS__REMOVE_NOTBOOLEAN_FILTERS"
};

export default types;